all: Evetar_AutoFocus

Evetar_AutoFocus:
	gcc -std=c++11 -o Evetar_AutoFocus Evetar_AutoFocus.cpp -lMantisAPI -lpthread -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lm -lstdc++

clean:
	rm Evetar_AutoFocus 
